name: Run Metal Storm Parser

on:
  schedule:
    # Запуск каждый понедельник в 06:00 UTC (9:00 по МСК)
    - cron: '0 6 * * 1'
  workflow_dispatch:
    # Кнопка ручного запуска с телефона на любой период
    inputs:
      month:
        description: 'Месяц (например: JUL, AUG, SEP, AUTO)'
        required: true
        default: 'AUTO'
      year:
        description: 'Год (например: 2026, AUTO)'
        required: true
        default: 'AUTO'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Execute Parser Script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: |
        python metalstorm.py ${{ github.event.inputs.month || 'AUTO' }} ${{ github.event.inputs.year || 'AUTO' }}
        
