name: Run Metal Test

on:
  workflow_dispatch: # Оставляем кнопку ручного запуска для тестов
  schedule:
    - cron: '0 12 * * 1' # Автоматический запуск каждый ПОНЕДЕЛЬНИК в 12:00 дня по Гринвичу

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Test Script
        run: python test_flag.py
