name: Run Metal Test

on:
  workflow_dispatch:
    inputs:
      month:
        description: 'Месяц (капсом: JUN, MAY, MAR) или оставь AUTO'
        required: true
        default: 'AUTO'
      year:
        description: 'Год релиза (например, 2026, 2025) или оставь AUTO'
        required: true
        default: 'AUTO'
        
  schedule:
    - cron: '0 12 * * 1' # Авто-запуск по понедельникам всегда работает в режиме AUTO

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Test Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        # Передаем введенные тобой месяц и год в Python-скрипт
        run: python test_flag.py "${{ github.event.inputs.month }}" "${{ github.event.inputs.year }}"
